### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by sinri0809** [sinri0809/sinriplayground#9]
- [ ] Redux -> Recoil로 변환 
- [ ] lazy loading 적용 
- [ ] google analytics
- [ ] Material UI custom
